# Generated by Django 2.2.16 on 2020-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hydroxide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('M', models.CharField(max_length=3)),
                ('X1', models.CharField(max_length=3)),
                ('X2', models.CharField(max_length=3)),
                ('Energy', models.TextField()),
            ],
        ),
    ]
